[package]
name = "randomos"
version = "0.2.0"
authors = ["Kushal Das <mail@kushaldas.in>"]
edition = "2021"
description = "Python module to learn"
documentation = "https://github.com/kushaldas/randomos/"
readme = "README.md"
homepage = "https://github.com/kushaldas/randomos"
repository = "https://github.com/kushaldas/randomos"
license-file = "LICENSE"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "randomos"
crate-type = ["cdylib"]

[dependencies]
<<<<<<< HEAD
pyo3 = { version = "0.21.2", features = ["extension-module"] }
<<<<<<< HEAD
<<<<<<< HEAD
sysinfo = "0.29.10"
=======
sysinfo = "0.17.0"
>>>>>>> 16a20fa (Adds Ros class)
=======
sysinfo = "0.29.10"
>>>>>>> 15342e9 (Updates sysinfo crate)


